//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apikatman
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        public int FirmaID { get; set; }
        public Nullable<int> AracID { get; set; }
        public Nullable<int> SoforID { get; set; }
        public string Firmaadi { get; set; }
        public string Firmatel { get; set; }
        public string Firmamail { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual Soforler Soforler { get; set; }
    }
}
