//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apikatman
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class muratvidanjorEntities : DbContext
    {
        public muratvidanjorEntities()
            : base("name=muratvidanjorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Araclar> Araclars { get; set; }
        public virtual DbSet<Firmalar> Firmalars { get; set; }
        public virtual DbSet<Soforler> Soforlers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
