//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apikatman
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soforler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soforler()
        {
            this.Araclars = new HashSet<Araclar>();
            this.Firmalars = new HashSet<Firmalar>();
        }
    
        public int SoforID { get; set; }
        public string Soforadi { get; set; }
        public string SoforSoyadi { get; set; }
        public string Sofortel { get; set; }
        public string Soformail { get; set; }
        public string Sofortc { get; set; }
        public string Soforehliyet { get; set; }
        public string Soforarac { get; set; }
        public Nullable<int> AracID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Araclar> Araclars { get; set; }
        public virtual Araclar Araclar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Firmalar> Firmalars { get; set; }
    }
}
